config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'dashboard#home'
  get  '/signup',  to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, only: [:show, :new, :create]
  resources :movies
  resources :cinemas do
    member do
      get :bookings
    end
  end
  resources :showings do
    collection do
      get :free_timeslots
    end
    member do
      get :bookings
    end
  end
  resources :bookings
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :logged_in_user,  only: [:admin]
  before_action :admin_user,      only: [:admin]

  def home
    @showings = Showing.paginate(page: params[:page], per_page: 5)
    @movies = Movie.paginate(page: params[:page], per_page: 5)
    @cinemas = Cinema.paginate(page: params[:page], per_page: 5)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_welcome.html.erb
<h1>Welcome to the Cinema Booking App!</h1>
<h2>
    Log in to start booking seats or click on the button below to sign up.
</h2>
<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>

app/views/dashboard/home.html.erb
<% unless logged_in? %>
    <div class="welcome-box">
        <div class="center jumbotron">
            <%= render 'welcome' %>
        </div>
    </div>
<% end %>

<section class="showings">
    <div class="flex">
        <h1 class="left">
            Showings
            <%= "(#{@showings.count})" if logged_in? && current_user.admin? %>
        </h1>

        <% if logged_in? && current_user.admin? %>
            <div class="admin-btn">
                <%= link_to "+ New Showing", new_showing_path,
                                        class: "btn btn-md btn-secondary" %>
            </div>
        <% end %>
    </div>

    <ul class="indices">
        <%= render @showings %>
    </ul>

    <%= will_paginate @showings %>
    <hr>
</section>

<section class="movies">
    <div class="flex">
        <h1 class="left">
            Movies
            <%= "(#{@movies.count})" if logged_in? && current_user.admin? %>
        </h1>

        <% if logged_in? && current_user.admin? %>
            <div class="admin-btn">
                <%= link_to "+ New Movie", new_movie_path,
                                       class: "btn btn-md btn-secondary" %>
            </div>
        <% end %>
    </div>

    <ul class="indices">
        <%= render @movies %>
    </ul>

    <%= will_paginate @movies %>
    <hr>
</section>

<section class="cinemas">
    <div class="flex">
        <h1 class="left">
            Cinemas
            <%= "(#{@cinemas.count})" if logged_in? && current_user.admin? %>
        </h1>

        <% if logged_in? && current_user.admin? %>
            <div class="admin-btn">
                <%= link_to "+ New Cinema", new_cinema_path,
                                        class: "btn btn-md btn-secondary" %>
            </div>
        <% end %>
    </div>

    <ul class="indices">
        <%= render @cinemas %>
    </ul>

    <%= will_paginate @cinemas %>
</section>