config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'dashboard#home'
  get  '/signup',  to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, only: [:show, :new, :create]
  resources :movies
  resources :cinemas do
    member do
      get :bookings
    end
  end
  resources :showings do
    collection do
      get :free_timeslots
    end
    member do
      get :bookings
    end
  end
  resources :bookings
end

app/models/showing.rb
class Showing < ApplicationRecord
  belongs_to :cinema
  belongs_to :movie
  has_many :bookings, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :cinema_id, presence: true
  validates :movie_id, presence: true
  validates :timeslot, presence: true
  validates :timeslot, uniqueness: { scope: :cinema,
                                     message: "for that cinema already taken" }
  
  # Returns list of seats that are already taken
  def booked_seats
    Booking.where(showing_id: id).pluck(:seat_number)
  end

  # Returns list of seats that are available for booking 
  def available_seats
    seats = self.cinema.seats
    booked = booked_seats
    (1..seats).reject { |seat| booked.include?(seat) }
  end
end

app/controllers/showings_controller.rb
class ShowingsController < ApplicationController
    before_action :logged_in_user,  only: [:new, :create, :destroy]
    before_action :admin_user,      only: [:new, :create, :destroy]

    def index
        @showings = Showing.paginate(page: params[:page])
    end

    def show
        @showing = Showing.find(params[:id])
    end

    def new
        @showing = Showing.new
        @cinemas = Cinema.all
        @movies = Movie.all
        @timeslots = [600, 840, 1080, 1320]
    end

    def create
        @showing = Showing.new(showing_params)
        if @showing.save
            flash[:success] = "Showing created"
            redirect_to @showing
        else
            @cinemas = Cinema.all
            @movies = Movie.all
            @timeslots = [600, 840, 1080, 1320]
            render 'new', status: :unprocessable_entity
        end
    end

    def destroy
        Showing.find(params[:id]).destroy
        flash[:success] = "Showing deleted"
        redirect_to root_url
    end

    # Returns list of available timeslots
    def free_timeslots
        timeslots = [600, 840, 1080, 1320]
        other_showings = Showing.where(cinema_id: params[:cinema_id]).pluck(:timeslot)
        @free_timeslots = timeslots.reject { |timeslot| other_showings.include?(timeslot) }
        @target = params[:target]
        respond_to do |format|
            format.turbo_stream
        end
    end

    def bookings
        @showing  = Showing.find(params[:id])
        @title = "Bookings | #{@showing.movie.title}"
        @bookings = @showing.bookings.paginate(page: params[:page])
        render 'showing_booking', status: :unprocessable_entity
    end

    private

        def showing_params
            params.require(:showing).permit(:timeslot, :cinema_id, :movie_id)
        end
end

app/helpers/showings_helper.rb
module ShowingsHelper

    # Returns timeslot formatted into words
    def time_in_words(time)
        hours, minutes = time.divmod(60)
        minutes = minutes.to_s.rjust(2, "0")    

        if hours >= 12
            period = "PM"
            hours-=12 unless hours == 12
        else
            period = "AM"
        end   

        "#{hours}:#{minutes}#{period}"
    end
end

app/views/showings/_form.html.erb
<%= form_with(model: @showing) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :movie_id %>
    <%= f.select :movie_id, @movies.map { |m| [ m.title, m.id ] },
                            { prompt: "Select movie" }, class: 'form-control' %>

    <div data-controller="select">
        <%= f.label :cinema_id %>
        <%= f.select :cinema_id, @cinemas.map { |c| [ c.name, c.id ] }, 
                                { prompt: "Select cinema" }, 
                                { class: 'form-control', 
                                  data: { action: "change->select#change" } } %>
        
        <%= f.label :timeslot %>
        <%= f.select :timeslot, @timeslots.map { |t| [ time_in_words(t), t ] }, 
                                {}, { class: 'form-control',
                                      data: { select_target: "tSelect" } } %>
    </div>

    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/showings/_showing.html.erb
<li>
    <h2><%= link_to showing.movie.title, showing %></h2>
    <%= time_in_words(showing.timeslot) %> | 
    <%= showing.cinema.name %> <br>
    Available Seats: <%= showing.available_seats.count %></p>

    <% if logged_in? && current_user.admin? %>
        <div class="buttons">
            <%= link_to "Bookings (#{showing.bookings.count})", bookings_showing_path(showing),
                                    class: "booking btn btn-sm btn-secondary" %>
            <%= link_to "Delete", showing, data: { "turbo-method": :delete,
                                                    turbo_confirm: "You sure?" },
                                           class: "btn btn-sm btn-danger" %>
        </div>
    <% end %>
</li>

app/views/showings/free_timeslots.turbo_stream.erb
<% turbo_stream.update @target do %>
    <% options_for_select @free_timeslots.map { |t| [ time_in_words(t), t ] } %>
<% end %>

app/views/showings/index.html.erb
<% provide(:title, 'All Showings') %>
<h1>All Showings</h1>

<%= will_paginate %>

<ul class="indices">
    <%= render @showings %>
</ul>

<%= will_paginate %>

app/views/showings/new.html.erb
<% provide(:title, 'New showing') %>
<% provide(:button_text, 'Create') %>
<h1>New Showing</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render 'form' %>
    </div>
</div>

app/views/showings/show.html.erb
<div class="flex">
    <h1 style="margin-bottom: 20px">
        <%= @showing.movie.title %>
    </h1>

    <% if logged_in? && current_user.admin? %>
        <div class="buttons">
            <%= link_to "Bookings (#{@showing.bookings.count})", bookings_showing_path(@showing),
                                    class: "booking btn btn-md btn-secondary" %>
            <%= link_to "Delete", @showing, data: { "turbo-method": :delete,
                                                   turbo_confirm: "You sure?" },
                                          class: "btn btn-md btn-danger" %>
        </div>
    <% end %>
</div>

<h5><%= time_in_words(@showing.timeslot) %></h5>
<h5><%= @showing.cinema.name %>, <%= @showing.cinema.location %></h5>
<h5>Available Seats: <%= @showing.available_seats.count %></h5>

<hr>

<h3>Synopsis</h3>
<p><%= @showing.movie.synopsis %></p>

<hr>

<div class="book-btn">
    <%= link_to "Book", new_booking_path(showing_id: @showing.id), class: "btn btn-lg btn-primary btn-block" %>
</div>

app/views/showings/showing_booking.html.erb
<div class="flex">
    <h1 style="margin-bottom: 20px">
        <%= @showing.movie.title %>
    </h1>

    <% if logged_in? && current_user.admin? %>
        <div class="buttons">
            <%= link_to "Delete", @showing, data: { "turbo-method": :delete,
                                                   turbo_confirm: "You sure?" },
                                          class: "btn btn-md btn-danger" %>
        </div>
    <% end %>
</div>

<h5><%= time_in_words(@showing.timeslot) %></h5>
<h5><%= @showing.cinema.name %>, <%= @showing.cinema.location %></h5>
<h5>Available Seats: <%= @showing.available_seats.count %></h5>

<hr>
<h3 class="left">Bookings (<%= @bookings.count %>)</h3>

<% if @bookings.any? %>    
    <ol class="indices">
        <%= render @bookings %>
    </ol>
    
    <%= will_paginate @bookings %>
<% end %>