config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'dashboard#home'
  get  '/signup',  to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, only: [:show, :new, :create]
  resources :movies
  resources :cinemas do
    member do
      get :bookings
    end
  end
  resources :showings do
    collection do
      get :free_timeslots
    end
    member do
      get :bookings
    end
  end
  resources :bookings
end

app/models/cinema.rb
class Cinema < ApplicationRecord
    validates :name, presence: true
    validates :location, presence: true
    validates :seats, presence: true, :inclusion => 1..10
    has_many :showings, dependent: :destroy
    has_many :bookings, through: :showings
    default_scope -> { order(created_at: :desc) }
end

app/controllers/cinemas_controller.rb
class CinemasController < ApplicationController
    before_action :logged_in_user,  only: [:new, :create, :edit, :update, :destroy, :bookings]
    before_action :admin_user,      only: [:new, :create, :edit, :update, :destroy, :bookings]

    def index
        @cinemas = Cinema.paginate(page: params[:page])
    end

    def show
        @cinema = Cinema.find(params[:id])
        @showings = @cinema.showings.paginate(page: params[:page])
    end

    def new
        @cinema = Cinema.new
    end

    def create
      @cinema = Cinema.new(cinema_params)
      if @cinema.save
        flash[:success] = "Cinema created"
        redirect_to @cinema
      else
        render 'new', status: :unprocessable_entity
      end
    end

    def edit
        @cinema = Cinema.find(params[:id])
    end

    def update
        @cinema = Cinema.find(params[:id])
        if @cinema.update(cinema_params)
            flash[:success] = "Cinema updated"
            redirect_to @cinema
        else
            render 'edit', status: :unprocessable_entity
        end
    end

    def destroy
        Cinema.find(params[:id]).destroy
        flash[:success] = "Cinema deleted"
        redirect_to root_url
    end

    def bookings
        @cinema  = Cinema.find(params[:id])
        @title = "Bookings | #{@cinema.name}"
        @bookings = @cinema.bookings.paginate(page: params[:page])
        render 'cinema_booking', status: :unprocessable_entity
    end

    private

        def cinema_params
            params.require(:cinema).permit(:name, :location, :seats)
        end
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/views/cinemas/_cinema.html.erb
<li>
    <h2><%= link_to cinema.name, cinema %></h2>
    <%= cinema.location %></p>

    <% if logged_in? && current_user.admin? %>
        <div class="buttons">
            <%= link_to "Bookings (#{cinema.bookings.count})", bookings_cinema_path(cinema),
                                class: "booking btn btn-sm btn-secondary" %>
            <%= link_to "Edit", edit_cinema_path(cinema),
                                    class: "btn btn-sm btn-primary" %>
            <%= link_to "Delete", cinema, data: { "turbo-method": :delete,
                                                    turbo_confirm: "You sure?" },
                                           class: "btn btn-sm btn-danger" %>
        </div>
    <% end %>
</li>

app/views/cinemas/_form.html.erb
<%= form_with(model: @cinema) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :location %>
    <%= f.text_field :location, class: 'form-control' %>

    <%= f.label :seats %>
    <%= f.number_field :seats, min: 1, max: 10, class: 'form-control' %>

    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/cinemas/cinema_booking.html.erb
<% provide(:title, @cinema.name) %>
<div class="flex">
    <h1 class="left"><%= @cinema.name %></h1>

    <% if logged_in? && current_user.admin? %>
        <div class="buttons">
            <%= link_to "Edit", edit_cinema_path(@cinema),
                                    class: "btn btn-md btn-primary" %>
            <%= link_to "Delete", @cinema, data: { "turbo-method": :delete,
                                                    turbo_confirm: "You sure?" },
                                           class: "btn btn-md btn-danger" %>
        </div>
    <% end %>
</div>

<h2 class="left"><%= @cinema.location %> | Seats: <%= @cinema.seats %></h2>

<hr>
<h3 class="left">Bookings (<%= @bookings.count %>)</h3>

<% if @bookings.any? %>
    <ol class="indices">
        <%= render @bookings %>
    </ol>
    
    <%= will_paginate @bookings %>
<% end %>

app/views/cinemas/edit.html.erb
<% provide(:title, "Edit Cinema") %>
<% provide(:button_text, 'Save changes') %>
<h1>Update Cinema</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render 'form' %>
    </div>
</div>

app/views/cinemas/index.html.erb
<% provide(:title, 'All Cinemas') %>
<h1>All Cinemas</h1>

<%= will_paginate %>

<ul class="indices">
    <%= render @cinemas %>
</ul>

<%= will_paginate %>

app/views/cinemas/new.html.erb
<% provide(:title, 'New Cinema') %>
<% provide(:button_text, 'Create') %>
<h1>New Cinema</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render 'form' %>
    </div>
</div>

app/views/cinemas/show.html.erb
<% provide(:title, @cinema.name) %>
<div class="flex">
    <h1 class="left"><%= @cinema.name %></h1>

    <% if logged_in? && current_user.admin? %>
        <div class="buttons">
            <%= link_to "Bookings (#{@cinema.bookings.count})", bookings_cinema_path(@cinema),
                                    class: "booking btn btn-md btn-secondary" %>
            <%= link_to "Edit", edit_cinema_path(@cinema),
                                    class: "btn btn-md btn-primary" %>
            <%= link_to "Delete", @cinema, data: { "turbo-method": :delete,
                                                    turbo_confirm: "You sure?" },
                                           class: "btn btn-md btn-danger" %>
        </div>
    <% end %>
</div>

<h2 class="left"><%= @cinema.location %> | Seats: <%= @cinema.seats %></h2>

<hr>
<h3 class="left">Showings (<%= @showings.count %>)</h3>

<% if @showings.any? %>
    <ol class="indices">
        <%= render @showings %>
    </ol>
    
    <%= will_paginate @showings %>
<% end %>