config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'dashboard#home'
  get  '/signup',  to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, only: [:show, :new, :create]
  resources :movies
  resources :cinemas do
    member do
      get :bookings
    end
  end
  resources :showings do
    collection do
      get :free_timeslots
    end
    member do
      get :bookings
    end
  end
  resources :bookings
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Cinema Booking App by Ieiaiel Sanceda
    </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "cinema booking", root_path, id: "logo" %>
        <nav>
            <div class="navbar-header">
                <button id="hamburger" type="button" class="navbar-toggle collapsed">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <ul id="navbar-menu" 
                class="nav navbar-nav navbar-right collapse navbar-collapse">
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Showings", showings_path %></li>
                <li><%= link_to "Movies", movies_path %></li>
                <li><%= link_to "Cinemas", cinemas_path %></li>
                <% if logged_in? %>
                    <li><%= link_to "User", current_user %></li>
                    <li>
                        <%= link_to "Log out", logout_path, 
                                               data: { "turbo-method": :delete } %>
                    </li>
                <% else %>
                    <li><%= link_to "Log in", login_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_rails_default.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>

      <%= yield %>

      <%= render 'layouts/footer' %>
      
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>